---
- name: Copy SSH Pub key out from localhost to the server's root accounts
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

- name: (For fun) print the Operating System and Machine Type
  ansible.builtin.debug:
    msg: '{{ ansible_architecture }} || {{ ansible_distribution | trim }} {{ ansible_distribution_major_version }}'

- name: Template a file to /etc/myhosts
  ansible.builtin.template:
    src: ../templates/hosts.j2
    dest: /etc/myhosts
    mode: '0644'
  when: inventory_hostname in groups['kubernetes']

# Again, I'd say let's copy /etc/hosts to local... but we're running NixOS rn
