---
- name: Set fact for encryption_key
  ansible.builtin.set_fact:
    encryption_key: "{{ lookup('community.general.random_string',length=32,base64=True) }}"

- name: Generate the Data Encryptuion Config and Key, and copy to master
  when: inventory_hostname in groups['masters']
  block:
    - name: Create the kube dir
      ansible.builtin.file:
        path: '{{ item }}'
        state: 'directory'
      loop:
        - '/var/lib/kubernetes'

    - name: Template out the encryption file
      ansible.builtin.template:
        src: '../templates/encryption-config.j2'
        dest: '/var/lib/kubernetes/encryption-config.yaml'

