---
- name: Kubernetes Cluster Boot Strap Process
  hosts: kubernetes

  vars_files: /Users/mkenkel/Repos/ansible-vault/farm-vault.yml

  vars:

  tasks:

    - name: Role call
      ansible.builtin.include_role:
        name: 03-compute-resources
